server:
  port: 8801

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: zuul-proxy
# 默认路由配置
zuul:
  routes:
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  prefix: /proxy
# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
